CREATE TABLE users(
    id SERIAL PRIMARY KEY NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    create at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP--PARA PODER CREAR UNA COLUMNA CON LA FECHA DE CREACION
)